export const ROUTES = {
  ROOT: "/",
  HOME: "/home",
  LOGIN: "/login",
  ADAPTATION: "/adaptation",
  EDUCATION_COURSES: "/education/courses",
  EDUCATION_EVENTS: "/education/events",
  EDUCATION_WEBINARS: "/education/webinars",
  EDUCATION_TESTS: "/education/tests",
  EDO_COURSES: "/edo/courses",
  EDO_EVENTS: "/edo/events",
  EDO_TESTS: "/edo/tests",
  MENTORSHIP: "/mentorship",
  MENTORSHIP_INTERNS: "/mentorship/interns",
  MENTORSHIP_INTERNS_PLAN_EDIT: "/mentorship/interns/:planId/edit",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_EDIT: "/admin/users/:userId",
  ADMIN_EDUCATION_COURSE: "/admin/education/courses",
  ADMIN_EDUCATION_EVENTS: "/admin/education/events",
  ADMIN_EDUCATION_WEBINARS: "/admin/education/webinars",
  ADMIN_EDUCATION_TESTS: "/admin/education/tests",
  ADMIN_EDO_COURSES: "/admin/edo/courses",
  ADMIN_EDO_EVENTS: "/admin/edo/events",
  ADMIN_EDO_TESTS: "/admin/edo/tests",
  ADMIN_ADAPTATION_TEMPLATES: "/admin/adaptation/templates",
  ADMIN_ADAPTATION_TEMPLATE_TASKS: "/admin/adaptation/templates/:templateId",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RouteValue = (typeof ROUTES)[RouteKey];
