export const ROUTES = {
  ROOT: "/",
  HOME: "/home",
  LOGIN: "/login",
  ADAPTATION: "/adaptation",
  LEARNING: "/learning",
  MENTORSHIP: "/mentorship",
  MENTORSHIP_INTERNS: "/mentorship/interns",
  MENTORSHIP_INTERNS_PLAN_CREATE: "/mentorship/interns/create",
  MENTORSHIP_INTERNS_PLAN_EDIT: "/mentorship/interns/:planId/edit",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_EDIT: "/admin/users/:userId",
  ADMIN_LEARNING: "/admin/learning",
  ADMIN_LEARNING_CREATE: "/admin/learning/create",
  ADMIN_LEARNING_EDIT: "/admin/learning/:id/edit",
  ADMIN_ADAPTATION_TEMPLATES: "/admin/adaptation/templates",
  ADMIN_ADAPTATION_TEMPLATES_CREATE: "/admin/adaptation/templates/create",
  ADMIN_ADAPTATION_TEMPLATE_TASKS: "/admin/adaptation/templates/:templateId",
} as const;
